# Kaiser-Meyer-Olkin (KMO) Test

In [1]:
kmo = function(data){
    library(MASS)
    X <- cor(as.matrix(data))
    iX <- ginv(X)
    S2 <- diag(diag((iX^-1)))
    AIS <- S2%*%iX%*%S2                      
    # anti-image covariance matrix
    IS <- X+AIS-2*S2
    # image covariance matrix
    Dai <- sqrt(diag(diag(AIS)))
    IR <- ginv(Dai)%*%IS%*%ginv(Dai)         
    # image correlation matrix
    AIR <- ginv(Dai)%*%AIS%*%ginv(Dai)       
    # anti-image correlation matrix
    a <- apply((AIR - diag(diag(AIR)))^2, 2, sum)
    AA <- sum(a)
    b <- apply((X - diag(nrow(X)))^2, 2, sum)
    BB <- sum(b)
    MSA <- b/(b+a)                        
    # indiv. measures of sampling adequacy
    AIR <- AIR-diag(nrow(AIR)) + diag(MSA)  
    # Examine the anti-image of the correlation matrix. That is the  negative of the partial correlations, partialling out all other variables.
    kmo <- BB/(AA+BB)                     
    # overall KMO statistic
    # Reporting the conclusion
    if (kmo >= 0.00 && kmo < 0.50){
        test <- 'Do not continue. KMO fail.'
    } else if (kmo >= 0.50 && kmo < 0.60){
        test <- 'Do not continue. KMO bad.'
    } else if (kmo >= 0.60 && kmo < 0.70){
        test <- 'Continue with caution. KMO is not good.'
    } else if (kmo >= 0.70 && kmo < 0.80){
        test <- 'Continue with caution. KMO is barely okay.' 
    } else if (kmo >= 0.80 && kmo < 0.90){
        test <- 'Continue. KMO is good.' 
    } else { 
        test <- 'Continue. KMO is excellent.' 
    }
    ans <- list( overall = kmo,report = test,individual = MSA,AIS = AIS,AIR = AIR )
    return(ans)
}

In [4]:
d <- read.csv('DS2IM.csv')

In [5]:
d[,c(1:3)]

traitX traitY traitZ
1    42     37     41    
2    51     58     52    
3    40     47     38    
4    45     74     68    
5    40     45     53    
6    43     40     48    
7    44     45     47    
8    41     58     45    
9    48     62     52    
10   41     65     44    
11   51     57     51    
12   46     78     49    
13   51     44     49    
14   50     42     35    
15   38     58     52    
16   28     39     55    
17   44     33     50    
18   39     61     60    
19   42     51     52    
20   43     36     44    
21   50     35     50    
22   42     64     41    
23   44     44     48    
24   61     31     49    
25   37     58     49    
26   56     53     46    
27   50     58     50    
28   52     40     61    
29   50     61     37    
30   58     62     69    
...  ...    ...    ...   
971  48     40     45    
972  38     57     47    
973  38     50     46    
974  38     56     56    
975  37     66     54    
976  63     48     45    
977  36     60     50    
978  47     59     45    
979  52     56     48    
980  34     41     50    
981  56     32     45    
982  32     72     44    
983  49     74     44    
984  48     51     68    
985  49     51     61    
986  35     53     52    
987  55     39     54    
988  50     45     38    
989  45     66     57    
990  43     55     47    
991  16     46     46    
992  47     68     53    
993  43     62     57    
994  23     64     41    
995  49     59     52    
996  45     35     52    
997  47     48     35    
998  53     64     60    
999  49     39     50    
1000 46     26     51

In [8]:
kmo(d[,c(1:3)])

$overall
[1] 0.4976877

$report
[1] "Do not continue. KMO fail."

$individual
   traitX    traitY    traitZ 
0.4984594 0.4983868 0.4690201 

$AIS
            [,1]         [,2]         [,3]
[1,]  0.97962263  0.136721872 -0.031252539
[2,]  0.13672187  0.980513439 -0.009369701
[3,] -0.03125254 -0.009369701  0.998975828

$AIR
            [,1]         [,2]         [,3]
[1,]  0.49845937  0.139502444 -0.031592094
[2,]  0.13950244  0.498386808 -0.009467198
[3,] -0.03159209 -0.009467198  0.469020108

In [11]:
d2 <- d[1:4]
d2

traitX traitY traitZ itemA
1    42     37     41     0    
2    51     58     52     0    
3    40     47     38     1    
4    45     74     68     0    
5    40     45     53     0    
6    43     40     48     0    
7    44     45     47     1    
8    41     58     45     1    
9    48     62     52     0    
10   41     65     44     0    
11   51     57     51     1    
12   46     78     49     1    
13   51     44     49     0    
14   50     42     35     1    
15   38     58     52     0    
16   28     39     55     0    
17   44     33     50     1    
18   39     61     60     1    
19   42     51     52     0    
20   43     36     44     0    
21   50     35     50     0    
22   42     64     41     0    
23   44     44     48     0    
24   61     31     49     1    
25   37     58     49     1    
26   56     53     46     1    
27   50     58     50     1    
28   52     40     61     0    
29   50     61     37     0    
30   58     62     69     1    
...  ...    ...    ...    ...  
971  48     40     45     1    
972  38     57     47     1    
973  38     50     46     1    
974  38     56     56     1    
975  37     66     54     1    
976  63     48     45     1    
977  36     60     50     0    
978  47     59     45     1    
979  52     56     48     1    
980  34     41     50     0    
981  56     32     45     1    
982  32     72     44     1    
983  49     74     44     0    
984  48     51     68     0    
985  49     51     61     1    
986  35     53     52     0    
987  55     39     54     0    
988  50     45     38     0    
989  45     66     57     0    
990  43     55     47     0    
991  16     46     46     1    
992  47     68     53     0    
993  43     62     57     1    
994  23     64     41     0    
995  49     59     52     1    
996  45     35     52     0    
997  47     48     35     0    
998  53     64     60     1    
999  49     39     50     0    
1000 46     26     51     1

In [10]:
kmo(d2)

$overall
[1] 0.4959839

$report
[1] "Do not continue. KMO fail."

$individual
   traitX    traitY    traitZ     itemA 
0.4923004 0.4959079 0.4966690 0.4969794 

$AIS
            [,1]        [,2]        [,3]        [,4]
[1,]  0.97928865  0.13688696 -0.03362889  0.01784670
[2,]  0.13688696  0.98034842 -0.01162307  0.01254602
[3,] -0.03362889 -0.01162307  0.95321590 -0.20409533
[4,]  0.01784670  0.01254602 -0.20409533  0.95399156

$AIR
            [,1]        [,2]        [,3]        [,4]
[1,]  0.49230040  0.13970646 -0.03480659  0.01846419
[2,]  0.13970646  0.49590789 -0.01202362  0.01297309
[3,] -0.03480659 -0.01202362  0.49666901 -0.21402533
[4,]  0.01846419  0.01297309 -0.21402533  0.49697941